using System;
using UnityEngine;


/// <summary>
/// This class contains methods for generating or deleting elements with brush.
/// </summary>
public class ElementSpawner
{
    private readonly ElementGrid elementGrid;

    public ElementSpawner(ElementGrid elementGrid)
    {
        this.elementGrid = elementGrid;
    }

    /// <summary>
    /// Spawn elements with given type in positions generated by given brush with center and x, y.
    /// </summary>
    public void SpawnElement(int x, int y, AbstractBrush brush, Type elementType)
    {
        foreach (Vector2Int position in brush.GetPositions(x, y))
        {
            elementGrid.SetElement(position.x, position.y, Activator.CreateInstance(elementType) as BaseElement);
        }
    }

    /// <summary>
    /// Deletes all elements in positions generated by given brush with center and x, y.
    /// </summary>
    public void Clear(int x, int y, AbstractBrush brush)
    {
        foreach (Vector2Int position in brush.GetPositions(x, y))
        {
            elementGrid.SetElement(position.x, position.y, null);
        }
    }
}
